### ISSUE TITLE
How to use the ServeStaticMiddleware?

### ISSUE THREAD

**Issue by marviobezerra** [wbhob/nest-middlewares#1]
I'm trying to use the ServeStaticMiddleware, but I don't know how to do it.

Can you post an example?

**Comment by wbhob** [comment]
You use it just like the example for Helmet in README. Import ServeStaticMiddleware from the package, and you can call `configure` to pass in your config, and then just use it like any other Nest middleware!

**Comment by wbhob** [comment]
Closing due to no response. I'll add readmes soon

**Comment by nurikabe** [comment]
Sorry to reopen this, but I'm a bit lost here as well.  As per the README, trying as follows in AppModule:

    ServeStaticMiddleware.configure('public/');
    consumer.apply(ServeStaticMiddleware).forRoutes('*');

Can't seem to find my public directory though.

Am I on the right track? Is `forRoutes()` actually relevant in this case?
