### ISSUE TITLE
Examples / documentation

### ISSUE THREAD

**Issue by jakobrosenberg** [wbhob/nest-middlewares#13]
I desperately need some form of documentation on how to implement ``nest-middlewares/express-session`` but my Google-fu has failed me.

**Comment by asantarissy** [comment]
Is this is what you are looking for? [expess-session README.md](https://github.com/wbhob/nest-middlewares/blob/master/packages/express-session/README.md)

**Comment by wbhob** [comment]
Everything is just a port of the package – these are just wrappers. You use them like you would the package itself, so please refer to the express session documentation.
