### ISSUE TITLE
problem in the docs

### ISSUE THREAD

**Issue by lilling** [wbhob/nest-middlewares#2]
I know its small but someone (yours truly 🥇) didn't understand the `ctrl+c` `crtl+v` bug:

in the serve-static readme (and my guess its for all of them) you write 
`HelmetMiddleware.configure( /* options as per helmet docs */ )`
**HelmetMiddleware**

**Comment by wbhob** [comment]
Thanks for letting me know! Fixed it.

**Comment by wbhob** [comment]
I'll go through and fix the others soon
