### ISSUE TITLE
Code bugs in CorsMiddleware

### ISSUE THREAD

**Issue by alexeytwolinkme** [wbhob/nest-middlewares#20]
Hi, I think there are a few issues with CorsMiddleware source code:

https://github.com/wbhob/nest-middlewares/blob/master/packages/cors/index.ts

Line 8 `this.options = opts;` should be `CorsMiddleware.options = opts;`
Line 17 `cors()(req, res, next);` should be wrapped with `else`, otherwise cors may be applied twice.

**Comment by wbhob** [comment]
can you make a pr please

**Comment by vip30** [comment]
Yes, my fault. 
I will make a pr later on
