### ISSUE TITLE
Support hide-powered-by

### ISSUE THREAD

**Issue by iangregsondev** [wbhob/nest-middlewares#21]
Hi,

great middleware, be nice if the following was supported also

https://helmetjs.github.io/docs/hide-powered-by/

**Comment by wbhob** [comment]
I'd be glad to review a PR with a wrapper around this package. Contributing guidelines: 
https://github.com/wbhob/nest-middlewares/blob/master/CONTRIBUTING.md

**Comment by vip30** [comment]
https://github.com/wbhob/nest-middlewares/blob/master/packages/helmet/hide-powered-by.ts

I guess it is already there?

**Comment by wbhob** [comment]
oh my bad yes - it is there. it's a wrapper around that part of helmet, so that's exactly what you need. Nice eye, @vip30 

Closing :)

**Comment by iangregsondev** [comment]
@vip30 Thanks, i assumed it wasn't supported as it wasn't listed as supported in the readme.

Thanks again
