### ISSUE TITLE
Nestjs 5 The @Middleware() decorator is deprecated

### ISSUE THREAD

**Issue by okhomenko** [wbhob/nest-middlewares#4]
With the latest version of nestjs it spits out an error:

**WARNING!!
The @Middleware() decorator is deprecated and will be removed within next major release. Use @Injectable() instead.**

**Comment by wbhob** [comment]
That is not an error, it is a warning. It still works, but just has an error. I will update it soon.

**Comment by wbhob** [comment]
all packages are now v5, and are updated to support NestJS v5. Cheers!
