### ISSUE TITLE
Errors update @nest-middleware/helmet@6.0.0 to 7.0.1

### ISSUE THREAD

**Issue by guiguialinea** [wbhob/nest-middlewares#65]
Hello :) 

Just to inform that on the last version of @nest-middlewares/helmet@7.0.1 the are some errors due to way of importing things from dist folder inside node_modules.

- Previously (version 6.0.0) helmet was added inside node modules trhough : 
       import * as helmet from 'helmet';
- Now each specific object is imported like this : 
       import { ContentSecurityPolicyOptions } from "helmet/dist/types/middlewares/content-security-policy";

But there is a problem because nowthere is no "dist" folder in node_modules.
I don't know a solution for this because i'm not familiar with javascript modules and how to generate them in typescript.
But i think it's about the dependencies of nest-middleware/helmet ?

Here are the files that lead errors : 
       node_modules/@nest-middlewares/helmet/content-security-policy.d.ts:2
       node_modules/@nest-middlewares/helmet/dns-prefetch-control.d.ts:2
       node_modules/@nest-middlewares/helmet/expect-ct.d.ts:2
       node_modules/@nest-middlewares/helmet/frameguard.d.ts:2
       node_modules/@nest-middlewares/helmet/hsts.d.ts:2
       node_modules/@nest-middlewares/helmet/referrer-policy.d.ts:2

Thanks in advance for your contributions to this package,
Have a great day,

**Comment by wbhob** [comment]
Just updated to latest helmet version. Please use package version 10.0.0
